### ISSUE TITLE
MacOS file format

### ISSUE THREAD

**Issue by notafir** [DoomHammer/songcorder#2]
Have tried downloading the mac os x file, all I get is a 'songcorder.dms' file that I am as yet unable to unpack/unarchive/unzip, changing the extension to .dmg leaves the macos 10.11.6 system telling me the image type is not recognised. I would have expexcted a .dmg .zip or .pkg file as a download for use on an apple system. Can you clarify if there is a particular utitlity that is required to accesss this file/wrapper or a particular process that should be followed. I'm not very familiar with command line processes

**Comment by JensArndt** [comment]
Hi notafir,
I am sure Doomhammer will eventually make Songcorder a nice "real program". I faced the same problems as you.  Please have a look at the user guide part 1.1. and 1.2 software installation to solve your problem.

**Comment by DoomHammer** [comment]
Hello @notafir  and thanks for the report!

I understand it is not very convenient right now to use `songcorder` on Mac. I am planning on releasing a "proper" version at some point in time, but at the moment all I can do is direct you to the guide mentioned by @JensArndt : https://doomhammer.github.io/songcorder/assets/the_guide.pdf

**Comment by DoomHammer** [comment]
Hi @notafir !

There's a new release for Mac. You can find it here: https://meraki-acoustic.com/songcorder
