### ISSUE TITLE
Error when running sox

### ISSUE THREAD

**Issue by garmtz** [DoomHammer/songcorder#5]
Dear DoomHammer,

Maybe this is not related to songcorder, but wanted to try to have it solved anyway if it isn't too much trouble...

I get the following error message running sox:

MacBook-van-Garmt:rips garmtvdz$ sox
dyld: Library not loaded: /usr/local/opt/mad/lib/libmad.0.dylib
  Referenced from: /usr/local/bin/sox
  Reason: image not found
Abort trap: 6

Any idea what could be wrong?

Thanks!

Kind regards,
Garmt

**Comment by DoomHammer** [comment]
Hello!

Sorry for a late reply. Personally, I don't own a Mac, but from what I see you are lacking one of necessary prerequisites for sox to work. From what I recall libmad is used for MPEG decoding, so this one should not be needed at all for songcorder to work.

Does this manifest in any way during normal songcorder operation?

**Comment by DoomHammer** [comment]
Hi @garmtz !

There's a new release for Mac. You can find it here: https://meraki-acoustic.com/songcorder
