### ISSUE TITLE
signal loss

### ISSUE THREAD

**Issue by tvaskjul** [DoomHammer/songcorder#9]
I am using songcorder to digitise some cassettes via my Linn Selekt with Katalyst.
I'm experiencing dropouts in the sound and notice when this happens the screen on the Selekt lights up. This usually only happens for a few seconds when you change source or when streaming and a new tracks starts. If I just play a cassette or LP it doesn't happen.

**Comment by DoomHammer** [comment]
Thanks for the report @tvaskjul !

As a general rule, switching inputs is not supported in Songcorder. For the best results,we also advise running both the DS and Songcorder on the same wired network.

There's also a new release available with nice GUI if you are interested. You can find it here: https://meraki-acoustic.com/songcorder
